# Generated by Django 3.1.2 on 2021-06-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('link', models.URLField()),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('articles', models.ManyToManyField(to='service.Article')),
            ],
        ),
        migrations.CreateModel(
            name='Bad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('qcode', models.CharField(max_length=32)),
                ('img', models.URLField()),
                ('drugs', models.ManyToManyField(to='service.Drug')),
            ],
        ),
    ]
