# Generated by Django 3.1.2 on 2021-06-18 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bad',
            name='drugs',
            field=models.ManyToManyField(blank=True, null=True, to='service.Drug'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='articles',
            field=models.ManyToManyField(blank=True, null=True, to='service.Article'),
        ),
    ]
