# Generated by Django 3.1.2 on 2021-06-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20210618_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='bad',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
