# Generated by Django 3.1.2 on 2021-06-18 21:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_bad_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='bad',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='bad',
            name='drug_count',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='bad',
            name='info',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bad',
            name='link',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bad',
            name='name',
            field=models.TextField(),
        ),
    ]
