# Generated by Django 3.1.2 on 2021-06-18 23:56

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_auto_20210618_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bad',
            name='categories',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='drug',
            name='name',
            field=models.TextField(),
        ),
    ]
