# Generated by Django 3.1.2 on 2021-06-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_auto_20210618_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.TextField(),
        ),
    ]
