# Generated by Django 3.1.2 on 2021-06-18 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_auto_20210618_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bad',
            name='count',
            field=models.TextField(),
        ),
    ]
